=== alex-ta/JavaXML/NewFile.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT root (bahn+,wagon*)>
<!ELEMENT bahn (schaffner)>
<!ELEMENT wagon EMPTY>
<!ELEMENT schaffner (#PCDATA)>
<!ATTLIST bahn name CDATA #REQUIRED
		  motorstaerke CDATA #IMPLIED
		  wagons IDREFS #IMPLIED >
<!ATTLIST schaffner name CDATA #REQUIRED>
<!ATTLIST wagon id ID #REQUIRED>

=== alex-ta/JavaXML/NewFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "NewFile.dtd">
<root>
<bahn name="Seetalbahn" motorstaerke="10" wagons="W1 W2 W3">
<schaffner name="Bernd">"Hey Leute"</schaffner>
</bahn>
<bahn name="Bergbahn" wagons ="W4">
<schaffner name="Heinz">"Guten Tag"</schaffner>
</bahn>

<wagon id ="W1"></wagon>
<wagon id ="W2"></wagon>
<wagon id ="W3"></wagon>
<wagon id ="W4"></wagon>
</root>
